//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfApp.SportsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Romo.net/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportsNews", Namespace="http://Romo.net/")]
    [System.SerializableAttribute()]
    public partial class SportsNews : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnippetField;
        
        private uint isBreakingNewsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Snippet {
            get {
                return this.SnippetField;
            }
            set {
                if ((object.ReferenceEquals(this.SnippetField, value) != true)) {
                    this.SnippetField = value;
                    this.RaisePropertyChanged("Snippet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public uint isBreakingNews {
            get {
                return this.isBreakingNewsField;
            }
            set {
                if ((this.isBreakingNewsField.Equals(value) != true)) {
                    this.isBreakingNewsField = value;
                    this.RaisePropertyChanged("isBreakingNews");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportsSchedule", Namespace="http://Romo.net/")]
    [System.SerializableAttribute()]
    public partial class SportsSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportsHighlights", Namespace="http://Romo.net/")]
    [System.SerializableAttribute()]
    public partial class SportsHighlights : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClickThroughPageUrlField;
        
        private uint RunTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaticThumbnailUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailWidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PageTitle {
            get {
                return this.PageTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PageTitleField, value) != true)) {
                    this.PageTitleField = value;
                    this.RaisePropertyChanged("PageTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceTitle {
            get {
                return this.SourceTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTitleField, value) != true)) {
                    this.SourceTitleField = value;
                    this.RaisePropertyChanged("SourceTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PlayUrl {
            get {
                return this.PlayUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayUrlField, value) != true)) {
                    this.PlayUrlField = value;
                    this.RaisePropertyChanged("PlayUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ClickThroughPageUrl {
            get {
                return this.ClickThroughPageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ClickThroughPageUrlField, value) != true)) {
                    this.ClickThroughPageUrlField = value;
                    this.RaisePropertyChanged("ClickThroughPageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public uint RunTime {
            get {
                return this.RunTimeField;
            }
            set {
                if ((this.RunTimeField.Equals(value) != true)) {
                    this.RunTimeField = value;
                    this.RaisePropertyChanged("RunTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StaticThumbnailUrl {
            get {
                return this.StaticThumbnailUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.StaticThumbnailUrlField, value) != true)) {
                    this.StaticThumbnailUrlField = value;
                    this.RaisePropertyChanged("StaticThumbnailUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ThumbnailWidth {
            get {
                return this.ThumbnailWidthField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailWidthField, value) != true)) {
                    this.ThumbnailWidthField = value;
                    this.RaisePropertyChanged("ThumbnailWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ThumbnailHeight {
            get {
                return this.ThumbnailHeightField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailHeightField, value) != true)) {
                    this.ThumbnailHeightField = value;
                    this.RaisePropertyChanged("ThumbnailHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ThumbnailSize {
            get {
                return this.ThumbnailSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailSizeField, value) != true)) {
                    this.ThumbnailSizeField = value;
                    this.RaisePropertyChanged("ThumbnailSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Romo.net/", ConfigurationName="SportsService.SportsInformationSoap")]
    public interface SportsInformationSoap {
        
        // CODEGEN: Generating message contract since element name topics from namespace http://Romo.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Romo.net/sportsNews", ReplyAction="*")]
        GolfApp.SportsService.sportsNewsResponse sportsNews(GolfApp.SportsService.sportsNewsRequest request);
        
        // CODEGEN: Generating message contract since element name league_team from namespace http://Romo.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Romo.net/sportsSchedules", ReplyAction="*")]
        GolfApp.SportsService.sportsSchedulesResponse sportsSchedules(GolfApp.SportsService.sportsSchedulesRequest request);
        
        // CODEGEN: Generating message contract since element name league_team from namespace http://Romo.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Romo.net/sportsVideoHighlights", ReplyAction="*")]
        GolfApp.SportsService.sportsVideoHighlightsResponse sportsVideoHighlights(GolfApp.SportsService.sportsVideoHighlightsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sportsNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sportsNews", Namespace="http://Romo.net/", Order=0)]
        public GolfApp.SportsService.sportsNewsRequestBody Body;
        
        public sportsNewsRequest() {
        }
        
        public sportsNewsRequest(GolfApp.SportsService.sportsNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Romo.net/")]
    public partial class sportsNewsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolfApp.SportsService.ArrayOfString topics;
        
        public sportsNewsRequestBody() {
        }
        
        public sportsNewsRequestBody(GolfApp.SportsService.ArrayOfString topics) {
            this.topics = topics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sportsNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sportsNewsResponse", Namespace="http://Romo.net/", Order=0)]
        public GolfApp.SportsService.sportsNewsResponseBody Body;
        
        public sportsNewsResponse() {
        }
        
        public sportsNewsResponse(GolfApp.SportsService.sportsNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Romo.net/")]
    public partial class sportsNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolfApp.SportsService.SportsNews[] sportsNewsResult;
        
        public sportsNewsResponseBody() {
        }
        
        public sportsNewsResponseBody(GolfApp.SportsService.SportsNews[] sportsNewsResult) {
            this.sportsNewsResult = sportsNewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sportsSchedulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sportsSchedules", Namespace="http://Romo.net/", Order=0)]
        public GolfApp.SportsService.sportsSchedulesRequestBody Body;
        
        public sportsSchedulesRequest() {
        }
        
        public sportsSchedulesRequest(GolfApp.SportsService.sportsSchedulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Romo.net/")]
    public partial class sportsSchedulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string league_team;
        
        public sportsSchedulesRequestBody() {
        }
        
        public sportsSchedulesRequestBody(string league_team) {
            this.league_team = league_team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sportsSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sportsSchedulesResponse", Namespace="http://Romo.net/", Order=0)]
        public GolfApp.SportsService.sportsSchedulesResponseBody Body;
        
        public sportsSchedulesResponse() {
        }
        
        public sportsSchedulesResponse(GolfApp.SportsService.sportsSchedulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Romo.net/")]
    public partial class sportsSchedulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolfApp.SportsService.SportsSchedule[] sportsSchedulesResult;
        
        public sportsSchedulesResponseBody() {
        }
        
        public sportsSchedulesResponseBody(GolfApp.SportsService.SportsSchedule[] sportsSchedulesResult) {
            this.sportsSchedulesResult = sportsSchedulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sportsVideoHighlightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sportsVideoHighlights", Namespace="http://Romo.net/", Order=0)]
        public GolfApp.SportsService.sportsVideoHighlightsRequestBody Body;
        
        public sportsVideoHighlightsRequest() {
        }
        
        public sportsVideoHighlightsRequest(GolfApp.SportsService.sportsVideoHighlightsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Romo.net/")]
    public partial class sportsVideoHighlightsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string league_team;
        
        public sportsVideoHighlightsRequestBody() {
        }
        
        public sportsVideoHighlightsRequestBody(string league_team) {
            this.league_team = league_team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sportsVideoHighlightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sportsVideoHighlightsResponse", Namespace="http://Romo.net/", Order=0)]
        public GolfApp.SportsService.sportsVideoHighlightsResponseBody Body;
        
        public sportsVideoHighlightsResponse() {
        }
        
        public sportsVideoHighlightsResponse(GolfApp.SportsService.sportsVideoHighlightsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Romo.net/")]
    public partial class sportsVideoHighlightsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GolfApp.SportsService.SportsHighlights[] sportsVideoHighlightsResult;
        
        public sportsVideoHighlightsResponseBody() {
        }
        
        public sportsVideoHighlightsResponseBody(GolfApp.SportsService.SportsHighlights[] sportsVideoHighlightsResult) {
            this.sportsVideoHighlightsResult = sportsVideoHighlightsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SportsInformationSoapChannel : GolfApp.SportsService.SportsInformationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SportsInformationSoapClient : System.ServiceModel.ClientBase<GolfApp.SportsService.SportsInformationSoap>, GolfApp.SportsService.SportsInformationSoap {
        
        public SportsInformationSoapClient() {
        }
        
        public SportsInformationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SportsInformationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportsInformationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportsInformationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolfApp.SportsService.sportsNewsResponse GolfApp.SportsService.SportsInformationSoap.sportsNews(GolfApp.SportsService.sportsNewsRequest request) {
            return base.Channel.sportsNews(request);
        }
        
        public GolfApp.SportsService.SportsNews[] sportsNews(GolfApp.SportsService.ArrayOfString topics) {
            GolfApp.SportsService.sportsNewsRequest inValue = new GolfApp.SportsService.sportsNewsRequest();
            inValue.Body = new GolfApp.SportsService.sportsNewsRequestBody();
            inValue.Body.topics = topics;
            GolfApp.SportsService.sportsNewsResponse retVal = ((GolfApp.SportsService.SportsInformationSoap)(this)).sportsNews(inValue);
            return retVal.Body.sportsNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolfApp.SportsService.sportsSchedulesResponse GolfApp.SportsService.SportsInformationSoap.sportsSchedules(GolfApp.SportsService.sportsSchedulesRequest request) {
            return base.Channel.sportsSchedules(request);
        }
        
        public GolfApp.SportsService.SportsSchedule[] sportsSchedules(string league_team) {
            GolfApp.SportsService.sportsSchedulesRequest inValue = new GolfApp.SportsService.sportsSchedulesRequest();
            inValue.Body = new GolfApp.SportsService.sportsSchedulesRequestBody();
            inValue.Body.league_team = league_team;
            GolfApp.SportsService.sportsSchedulesResponse retVal = ((GolfApp.SportsService.SportsInformationSoap)(this)).sportsSchedules(inValue);
            return retVal.Body.sportsSchedulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GolfApp.SportsService.sportsVideoHighlightsResponse GolfApp.SportsService.SportsInformationSoap.sportsVideoHighlights(GolfApp.SportsService.sportsVideoHighlightsRequest request) {
            return base.Channel.sportsVideoHighlights(request);
        }
        
        public GolfApp.SportsService.SportsHighlights[] sportsVideoHighlights(string league_team) {
            GolfApp.SportsService.sportsVideoHighlightsRequest inValue = new GolfApp.SportsService.sportsVideoHighlightsRequest();
            inValue.Body = new GolfApp.SportsService.sportsVideoHighlightsRequestBody();
            inValue.Body.league_team = league_team;
            GolfApp.SportsService.sportsVideoHighlightsResponse retVal = ((GolfApp.SportsService.SportsInformationSoap)(this)).sportsVideoHighlights(inValue);
            return retVal.Body.sportsVideoHighlightsResult;
        }
    }
}
