#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="courseDB")]
public partial class courseClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertcourse(course instance);
  partial void Updatecourse(course instance);
  partial void Deletecourse(course instance);
  #endregion
	
	public courseClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["courseDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public courseClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public courseClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public courseClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public courseClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<course> courses
	{
		get
		{
			return this.GetTable<course>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.courses")]
public partial class course : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _courseID;
	
	private string _code;
	
	private string _title;
	
	private string _instructor;
	
	private System.Nullable<int> _cap;
	
	private System.Nullable<int> _ccode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncourseIDChanging(int value);
    partial void OncourseIDChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OninstructorChanging(string value);
    partial void OninstructorChanged();
    partial void OncapChanging(System.Nullable<int> value);
    partial void OncapChanged();
    partial void OnccodeChanging(System.Nullable<int> value);
    partial void OnccodeChanged();
    #endregion
	
	public course()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int courseID
	{
		get
		{
			return this._courseID;
		}
		set
		{
			if ((this._courseID != value))
			{
				this.OncourseIDChanging(value);
				this.SendPropertyChanging();
				this._courseID = value;
				this.SendPropertyChanged("courseID");
				this.OncourseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string code
	{
		get
		{
			return this._code;
		}
		set
		{
			if ((this._code != value))
			{
				this.OncodeChanging(value);
				this.SendPropertyChanging();
				this._code = value;
				this.SendPropertyChanged("code");
				this.OncodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instructor", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string instructor
	{
		get
		{
			return this._instructor;
		}
		set
		{
			if ((this._instructor != value))
			{
				this.OninstructorChanging(value);
				this.SendPropertyChanging();
				this._instructor = value;
				this.SendPropertyChanged("instructor");
				this.OninstructorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cap", DbType="Int")]
	public System.Nullable<int> cap
	{
		get
		{
			return this._cap;
		}
		set
		{
			if ((this._cap != value))
			{
				this.OncapChanging(value);
				this.SendPropertyChanging();
				this._cap = value;
				this.SendPropertyChanged("cap");
				this.OncapChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccode", DbType="Int")]
	public System.Nullable<int> ccode
	{
		get
		{
			return this._ccode;
		}
		set
		{
			if ((this._ccode != value))
			{
				this.OnccodeChanging(value);
				this.SendPropertyChanging();
				this._ccode = value;
				this.SendPropertyChanged("ccode");
				this.OnccodeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
