<?xml version="1.0" encoding="utf-8"?><Database Name="courseDB" Class="courseClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\courseDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="courseDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.courses" Member="courses">
    <Type Name="course">
      <Column Name="courseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="title" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="instructor" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ccode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>