<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="messageClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.messageServer" Member="messageServers">
    <Type Name="messageServer">
      <Column Name="senderID" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="receiverID" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="timestamp" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="msg" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="msgID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>