## Makefile for rotate -- updated 09/07/2010

CC		= gcc
CC_OPTIONS	= -g -ansi -pedantic -Wall

rotate:	rotate.c
	$(CC) -o rotate $(CC_OPTIONS) rotate.c

clean:
	rm -f rotate a.out core *.o

## end of Makefile
